// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.API.Data;

namespace Store.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Store.API.Models.Bill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBills");

                    b.Property<int?>("OwnerFactoryUserId");

                    b.Property<int?>("PhotoUrlId");

                    b.Property<double>("payed");

                    b.Property<int?>("regiteredIdUser");

                    b.HasKey("id");

                    b.HasIndex("OwnerFactoryUserId");

                    b.HasIndex("PhotoUrlId");

                    b.HasIndex("regiteredIdUser");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Store.API.Models.BillsClothes", b =>
                {
                    b.Property<int>("ClothesCode");

                    b.Property<int>("BillsId");

                    b.Property<double>("PriceFactory");

                    b.Property<int>("Quentity");

                    b.HasKey("ClothesCode");

                    b.HasIndex("BillsId");

                    b.ToTable("BillsClothes");
                });

            modelBuilder.Entity("Store.API.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Store.API.Models.CategoryPrefered", b =>
                {
                    b.Property<int>("CategoryId");

                    b.Property<int>("ClientId");

                    b.HasKey("CategoryId");

                    b.HasIndex("ClientId");

                    b.ToTable("CategoryPrefereds");
                });

            modelBuilder.Entity("Store.API.Models.Cleint", b =>
                {
                    b.Property<int>("UserId");

                    b.HasKey("UserId");

                    b.ToTable("Cleints");
                });

            modelBuilder.Entity("Store.API.Models.ClientBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBills");

                    b.Property<string>("Location");

                    b.Property<bool>("TypePaid");

                    b.Property<bool>("isRecieved");

                    b.Property<double>("paid");

                    b.HasKey("Id");

                    b.ToTable("clientBills");
                });

            modelBuilder.Entity("Store.API.Models.ClientBillClothes", b =>
                {
                    b.Property<int>("ClientBillId");

                    b.Property<int>("ClothId");

                    b.Property<int>("Quentity");

                    b.Property<double>("Sale");

                    b.HasKey("ClientBillId");

                    b.HasIndex("ClothId");

                    b.ToTable("clientBillClothes");
                });

            modelBuilder.Entity("Store.API.Models.Cloth", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Categoryid");

                    b.Property<long>("Color");

                    b.Property<string>("Description");

                    b.Property<bool>("MainPhoto");

                    b.Property<string>("ModelName");

                    b.Property<string>("PhotoUrl");

                    b.Property<double>("Price");

                    b.Property<string>("PublicId");

                    b.Property<int>("Quentity");

                    b.Property<double>("Sale");

                    b.Property<int?>("Sizeid");

                    b.Property<int?>("TypeClothid");

                    b.Property<bool>("isApproved");

                    b.HasKey("Code");

                    b.HasIndex("Categoryid");

                    b.HasIndex("Sizeid");

                    b.HasIndex("TypeClothid");

                    b.ToTable("Clothes");
                });

            modelBuilder.Entity("Store.API.Models.Distributor", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("CarNumbers");

                    b.Property<double>("NumOfgears");

                    b.Property<double>("Percantage");

                    b.Property<double>("Salary");

                    b.Property<string>("Type");

                    b.HasKey("UserId");

                    b.ToTable("Distributor");
                });

            modelBuilder.Entity("Store.API.Models.Employee", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<double>("Allowances");

                    b.Property<double>("Incentives");

                    b.Property<double>("Salary");

                    b.HasKey("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Store.API.Models.OwnerFactory", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("Address");

                    b.Property<int>("LogoId");

                    b.Property<string>("Name");

                    b.Property<string>("phone");

                    b.HasKey("UserId");

                    b.HasIndex("LogoId");

                    b.ToTable("OwnerFactories");
                });

            modelBuilder.Entity("Store.API.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Description");

                    b.Property<bool>("IsApproved");

                    b.Property<string>("PublicId");

                    b.Property<string>("Url");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Store.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Store.API.Models.Size", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("id");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("Store.API.Models.SizePrefered", b =>
                {
                    b.Property<int>("SizeId");

                    b.Property<int>("CleintId");

                    b.HasKey("SizeId");

                    b.HasIndex("CleintId");

                    b.ToTable("SizePrefereds");
                });

            modelBuilder.Entity("Store.API.Models.TypeCloth", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("id");

                    b.ToTable("typeClothes");
                });

            modelBuilder.Entity("Store.API.Models.TypeClothPrefered", b =>
                {
                    b.Property<int>("TypeClothId");

                    b.Property<int>("CleintId");

                    b.HasKey("TypeClothId");

                    b.HasIndex("CleintId");

                    b.ToTable("TypeClothPrefereds");
                });

            modelBuilder.Entity("Store.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("City");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Country");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("Gender");

                    b.Property<string>("Interests");

                    b.Property<string>("Introduction");

                    b.Property<string>("KnownAs");

                    b.Property<DateTime>("LastActive");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("LookingFor");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Store.API.Models.UserRole", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Store.API.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Store.API.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Store.API.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Store.API.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Store.API.Models.Bill", b =>
                {
                    b.HasOne("Store.API.Models.OwnerFactory", "OwnerFactory")
                        .WithMany()
                        .HasForeignKey("OwnerFactoryUserId");

                    b.HasOne("Store.API.Models.Photo", "PhotoUrl")
                        .WithMany()
                        .HasForeignKey("PhotoUrlId");

                    b.HasOne("Store.API.Models.Employee", "regiteredId")
                        .WithMany()
                        .HasForeignKey("regiteredIdUser");
                });

            modelBuilder.Entity("Store.API.Models.BillsClothes", b =>
                {
                    b.HasOne("Store.API.Models.Bill", "Bill")
                        .WithMany("BillsClothes")
                        .HasForeignKey("BillsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Store.API.Models.Cloth", "Cloth")
                        .WithMany()
                        .HasForeignKey("ClothesCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Store.API.Models.CategoryPrefered", b =>
                {
                    b.HasOne("Store.API.Models.Category", "Category")
                        .WithMany("CategoryPrefereds")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Store.API.Models.Cleint", "Cleint")
                        .WithMany("CategoryPrefered")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Store.API.Models.Cleint", b =>
                {
                    b.HasOne("Store.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Store.API.Models.ClientBillClothes", b =>
                {
                    b.HasOne("Store.API.Models.ClientBill", "ClientBill")
                        .WithMany("ClientBillClothes")
                        .HasForeignKey("ClientBillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Store.API.Models.Cloth", "Cloth")
                        .WithMany("ClientBillClothes")
                        .HasForeignKey("ClothId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Store.API.Models.Cloth", b =>
                {
                    b.HasOne("Store.API.Models.Category", "Category")
                        .WithMany("Clothes")
                        .HasForeignKey("Categoryid");

                    b.HasOne("Store.API.Models.Size", "Size")
                        .WithMany("Clothes")
                        .HasForeignKey("Sizeid");

                    b.HasOne("Store.API.Models.TypeCloth", "TypeCloth")
                        .WithMany("Clothes")
                        .HasForeignKey("TypeClothid");
                });

            modelBuilder.Entity("Store.API.Models.Distributor", b =>
                {
                    b.HasOne("Store.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Store.API.Models.Employee", b =>
                {
                    b.HasOne("Store.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Store.API.Models.OwnerFactory", b =>
                {
                    b.HasOne("Store.API.Models.Photo", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Store.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Store.API.Models.Photo", b =>
                {
                    b.HasOne("Store.API.Models.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Store.API.Models.SizePrefered", b =>
                {
                    b.HasOne("Store.API.Models.Cleint", "Cleint")
                        .WithMany("SizePrefered")
                        .HasForeignKey("CleintId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Store.API.Models.Size", "Size")
                        .WithMany("SizePrefereds")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Store.API.Models.TypeClothPrefered", b =>
                {
                    b.HasOne("Store.API.Models.Cleint", "Cleint")
                        .WithMany("TypeClothPrefered")
                        .HasForeignKey("CleintId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Store.API.Models.TypeCloth", "TypeCloth")
                        .WithMany("CategoryPrefereds")
                        .HasForeignKey("TypeClothId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Store.API.Models.UserRole", b =>
                {
                    b.HasOne("Store.API.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Store.API.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
